In [1]:
import numpy as np

In [144]:
# Количество клеток по вертикали и горизонтали
rows, cols = 5, 5

# Коэффициент обесценивания
gamma = 0.9

# Штраф за шаг за пределы поля
penalty = -1

# Создаем матрицу коэффициентов
A = np.zeros((rows * cols, rows * cols))
b = np.zeros(rows * cols)

In [145]:
for i in range(rows):
    for j in range(cols):
        index = i * cols + j  # Индекс текущей клетки в одномерном представлении
        A[index, index] = -1  # Коэффициент при V(s)
        
        neighbors = [(i-1, j), (i+1, j), (i, j-1), (i, j+1)]  # Соседние клетки

        for neighbor_i, neighbor_j in neighbors:
            if 0 <= neighbor_i < rows and 0 <= neighbor_j < cols:
                neighbor_index = neighbor_i * cols + neighbor_j
                A[index, neighbor_index] += gamma / 4  # Дисконтирование
            else:
                # Штраф за выход за пределы поля
                b[index] -= penalty / 4  # Штраф добавляется к вектору свободных членов

        # Заполняем вектор свободных членов
        if (i, j) == (0, 1):  # Клетка A
            next_index = 4 * cols + 1  # индекс A`
            A[index, next_index] = gamma
            b[index] = -10
        elif (i, j) == (0, 3):  # Клетка B
            next_index = 2 * cols + 3  # индекс B`
            A[index, next_index] = gamma
            b[index] = -5

In [146]:
# Решаем систему уравнений
V = np.linalg.solve(A, b)

In [147]:
# Выводим результаты
V_matrix = V.reshape((rows, cols))
print("Функции ценности состояния:")
print(V_matrix)

Функции ценности состояния:
[[ 2.51504644 12.14251992  4.90150614  7.8706662   1.42920104]
 [ 1.25768649  3.94328156  2.88239672  2.78277356  0.70356063]
 [ 0.24250085  1.24309268  1.18309082  0.91125893  0.02607265]
 [-0.31188651  0.15598314  0.22143309  0.05810266 -0.38782999]
 [-0.67353516 -0.45938085 -0.41302954 -0.48662798 -0.69675304]]
